# Generated by Django 2.1 on 2018-08-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180803_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ManyToManyField(related_name='likes', to='posts.Post'),
        ),
    ]
